### ISSUE TITLE
Optimize SceneView Method

### ISSUE THREAD

**Issue by nicrobkal** [ttalexander2/chroma#25]
**Describe the bug**
SceneView program needs optimization.

**To Reproduce**
1. Go to Scene.h in Chroma
2. Enter the Scene class and subclass SceneView
3. See unoptimized code

**Expected behavior**
Needs a more optimized algorithm for the SceneView loop. Current efficiency is O(n)+.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: All

**Smartphone (please complete the following information):**
 - N/A

**Additional context**

**Comment by ttalexander2** [comment]
Fixed by replacing ECS solution with EnTT
